In [17]:
import pandas as pd
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris,fetch_california_housing
from sklearn.tree import DecisionTreeClassifier,DecisionTreeRegressor

In [18]:
data=load_iris()
data
df=pd.DataFrame(data.data,columns=data.feature_names)
df["species"]=data.target
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [19]:
X=df.drop("species",axis=1)
y=df.species

In [20]:
Xtrain,Xtest,ytrain,ytest=train_test_split(X,y,test_size=0.3,random_state=42)

In [21]:
model=DecisionTreeClassifier(max_depth=5)
model.fit(Xtrain,ytrain)

DecisionTreeClassifier(max_depth=5)

In [22]:
DecisionTreeClassifier(max_depth=5)

DecisionTreeClassifier(max_depth=5)

In [23]:
ypred=model.predict(Xtest)
ypred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0])

In [24]:
confusion_matrix(ytest,ypred)

array([[19,  0,  0],
       [ 0, 13,  0],
       [ 0,  0, 13]])

In [25]:
print("Training Efficiency :",model.score(Xtrain,ytrain))
print("Training Efficiency :",model.score(Xtest,ytest))

Training Efficiency : 1.0
Training Efficiency : 1.0

In [26]:
print('Accuracy score :',accuracy_score(ytest,ypred))
print('Precision score',precision_score(ytest,ypred,average="weighted"))
print('Recall Score',recall_score(ytest,ypred,average="weighted"))

Accuracy score : 1.0
Precision score 1.0
Recall Score 1.0

In [27]:
df=pd.read_csv("https://github.com/Jeevita-R/ML_datasets/raw/refs/heads/main/House_price_prediction.csv")
df.head()

,Unnamed: 0,Suburb,Rooms,Type,Method,SellerG,Regionname,Propertycount,Distance,CouncilArea,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price
0,1,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,1.0,202.0,160.2564,1480000.0
1,2,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,0.0,156.0,79.0000,1035000.0
2,4,Abbotsford,3,h,SP,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,2.0,0.0,134.0,150.0000,1465000.0
3,5,Abbotsford,3,h,PI,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,2.0,1.0,94.0,160.2564,850000.0
4,6,Abbotsford,4,h,VB,Nelson,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,1.0,2.0,120.0,142.0000,1600000.0

In [28]:
df=df.drop("Unnamed: 0",axis=1)
df

,Suburb,Rooms,Type,Method,SellerG,Regionname,Propertycount,Distance,CouncilArea,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price
0,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,1.0,202.000000,160.2564,1480000.0
1,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,0.0,156.000000,79.0000,1035000.0
2,Abbotsford,3,h,SP,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,2.0,0.0,134.000000,150.0000,1465000.0
3,Abbotsford,3,h,PI,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,2.0,1.0,94.000000,160.2564,850000.0
4,Abbotsford,4,h,VB,Nelson,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,1.0,2.0,120.000000,142.0000,1600000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27239,Yarraville,4,h,PI,Jas,Western Metropolitan,6543.0,6.3,Maribyrnong City Council,4.0,1.0,3.0,593.000000,160.2564,1480000.0
27240,Yarraville,2,h,SP,Sweeney,Western Metropolitan,6543.0,6.3,Maribyrnong City Council,2.0,2.0,1.0,98.000000,104.0000,888000.0
27241,Yarraville,2,t,S,Jas,Western Metropolitan,6543.0,6.3,Maribyrnong City Council,2.0,1.0,2.0,220.000000,120.0000,705000.0
27242,Yarraville,3,h,SP,hockingstuart,Western Metropolitan,6543.0,6.3,Maribyrnong City Council,0.0,0.0,0.0,593.598993,160.2564,1140000.0
27243,Yarraville,2,h,PI,RW,Western Metropolitan,6543.0,6.3,Maribyrnong City Council,2.0,1.0,0.0,250.000000,103.0000,1020000.0

In [ ]:
df=pd.get_dummies(df,dtype=int,drop_first=True)
df.head

<bound method NDFrame.head of        Rooms  Propertycount  Distance  Bedroom2  Bathroom  Car    Landsize  \
0          2         4019.0       2.5       2.0       1.0  1.0  202.000000
1          2         4019.0       2.5       2.0       1.0  0.0  156.000000
2          3         4019.0       2.5       3.0       2.0  0.0  134.000000
3          3         4019.0       2.5       3.0       2.0  1.0   94.000000
4          4         4019.0       2.5       3.0       1.0  2.0  120.000000
...      ...            ...       ...       ...       ...  ...         ...
27239      4         6543.0       6.3       4.0       1.0  3.0  593.000000
27240      2         6543.0       6.3       2.0       2.0  1.0   98.000000
27241      2         6543.0       6.3       2.0       1.0  2.0  220.000000
27242      3         6543.0       6.3       0.0       0.0  0.0  593.598993
27243      2         6543.0       6.3       2.0       1.0  0.0  250.000000

       BuildingArea      Price  Suburb_Aberfeldie  ...  \
0          160.2564  1480000.0                  0  ...
1           79.0000  1035000.0                  0  ...
2          150.0000  1465000.0                  0  ...
3          160.2564   850000.0                  0  ...
4          142.0000  1600000.0                  0  ...
...             ...        ...                ...  ...
27239      160.2564  1480000.0                  0  ...
27240      104.0000   888000.0                  0  ...
27241      120.0000   705000.0                  0  ...
27242      160.2564  1140000.0                  0  ...
27243      103.0000  1020000.0                  0  ...

       CouncilArea_Moorabool Shire Council  CouncilArea_Moreland City Council  \
0                                        0                                  0
1                                        0                                  0
2                                        0                                  0
3                                        0                                  0
4                                        0                                  0
...                                    ...                                ...
27239                                    0                                  0
27240                                    0                                  0
27241                                    0                                  0
27242                                    0                                  0
27243                                    0                                  0

       CouncilArea_Nillumbik Shire Council  \
0                                        0
1                                        0
2                                        0
3                                        0
4                                        0
...                                    ...
27239                                    0
27240                                    0
27241                                    0
27242                                    0
27243                                    0

       CouncilArea_Port Phillip City Council  \
0                                          0
1                                          0
2                                          0
3                                          0
4                                          0
...                                      ...
27239                                      0
27240                                      0
27241                                      0
27242                                      0
27243                                      0

       CouncilArea_Stonnington City Council  \
0                                         0
1                                         0
2                                         0
3                                         0
4                                         0
...                                     ...
27239                                     0
27240                                     0
27241                                     0
27242                                     0
27243                                     0

       CouncilArea_Whitehorse City Council  \
0                                        0
1                                        0
2                                        0
3                                        0
4                                        0
...                                    ...
27239                                    0
27240                                    0
27241                                    0
27242                                    0
27243                                    0

       CouncilArea_Whittlesea City Council  CouncilArea_Wyndham City Council  \
0                                        0                                 0
1                                        0                                 0
2                                        0                                 0
3                                        0                                 0
4                                        0                                 0
...                                    ...                               ...
27239                                    0                                 0
27240                                    0                                 0
27241                                    0                                 0
27242                                    0                                 0
27243                                    0                                 0

       CouncilArea_Yarra City Council  CouncilArea_Yarra Ranges Shire Council
0                                   1                                       0
1                                   1                                       0
2                                   1                                       0
3                                   1                                       0
4                                   1                                       0
...                               ...                                     ...
27239                               0                                       0
27240                               0                                       0
27241                               0                                       0
27242                               0                                       0
27243                               0                                       0

[27244 rows x 745 columns]>

In [34]:
X=df.drop("Price",axis=1)
y=df.Price

In [35]:
Xtrain,Xtest,ytrain,ytest=train_test_split(X,y,test_size=0.3,random_state=42)

In [36]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
Xtrain=scaler.fit_transform(Xtrain)
Xtest=scaler.transform(Xtest)

In [37]:
model=DecisionTreeRegressor(max_depth=5)
model.fit(Xtrain,ytrain)

DecisionTreeRegressor(max_depth=5)

In [38]:
ypred=model.predict(Xtest)
ypred

array([ 716826.9461642 , 1100342.2431526 ,  716826.9461642 , ...,
        716826.9461642 ,  840275.99164927, 1100342.2431526 ],
      shape=(8174,))

In [39]:
print("Training Efficiency :",model.score(Xtrain,ytrain))
print("Training Efficiency :",model.score(Xtest,ytest))

Training Efficiency : 0.6132832039783052
Training Efficiency : 0.6058440807644814

In [41]:
print("mae: ",mean_absolute_error(ytest,ypred))
print("R2 Score :", r2_score(ytest, ypred))

mae:  258513.94017153943
R2 Score : 0.6058440807644814