In [ ]:
# import numpy as np
import pandas as pd
# import matplotlib as md
# import seaborn as sb
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import Normalizer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.linear_model import Lasso
from sklearn.datasets import load_breast_cancer

In [7]:
#labelEncoder
LE=LabelEncoder()
df=pd.DataFrame({'Gender':['Male','Female','Male','Female','Female']})
data=LE.fit_transform(df['Gender'])
df['Encoded_Gender']=data
df

   Gender  Encoded_Gender
0    Male               1
1  Female               0
2    Male               1
3  Female               0
4  Female               0

In [8]:
#oneHotEncoders
OHE=OneHotEncoder(sparse_output=False)          #sparse_output for dense matrix
df1=pd.DataFrame({'products':['laptop','Ac','tv','Mobile','Laptop','AC','fridge']})
data=OHE.fit_transform(df1[['products']])
names=OHE.get_feature_names_out(['products'])
df=pd.DataFrame(data,columns=names)
# Add original column
df['Products'] = df1
# Fancy indexing
df = df[df.columns[[-1, 0, 1, 2,3]]]
print(df)

  Products  products_AC  products_Ac  products_Laptop  products_Mobile
0   laptop          0.0          0.0              0.0              0.0
1       Ac          0.0          1.0              0.0              0.0
2       tv          0.0          0.0              0.0              0.0
3   Mobile          0.0          0.0              0.0              1.0
4   Laptop          0.0          0.0              1.0              0.0
5       AC          1.0          0.0              0.0              0.0
6   fridge          0.0          0.0              0.0              0.0

In [9]:
df = pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/hr_data.csv')
df.head()
df['department'].unique()

array(['sales', 'accounting', 'hr', 'technical', 'support', 'management',
       'IT', 'product_mng', 'marketing', 'RandD'], dtype=object)

In [10]:
OHE=OneHotEncoder(sparse_output=False)  
data=OHE.fit_transform(df[['department']])
names=OHE.get_feature_names_out(['department'])
df1=pd.DataFrame(data,columns=names)
df

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,support,low
14995,87673,2,160,3,0,1,0,support,low
14996,87679,2,143,3,0,1,0,support,low
14997,87681,6,280,4,0,1,0,support,low
14998,87684,2,158,3,0,1,0,support,low

In [11]:
df=pd.get_dummies(df,dtype=int,drop_first=True)
df

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department_RandD,department_accounting,department_hr,department_management,department_marketing,department_product_mng,department_sales,department_support,department_technical,salary_low,salary_medium
0,1003,2,157,3,0,1,0,0,0,0,0,0,0,1,0,0,1,0
1,1005,5,262,6,0,1,0,0,0,0,0,0,0,1,0,0,0,1
2,1486,7,272,4,0,1,0,0,0,0,0,0,0,1,0,0,0,1
3,1038,5,223,5,0,1,0,0,0,0,0,0,0,1,0,0,1,0
4,1057,2,159,3,0,1,0,0,0,0,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,0,0,0,0,0,0,0,1,0,1,0
14995,87673,2,160,3,0,1,0,0,0,0,0,0,0,0,1,0,1,0
14996,87679,2,143,3,0,1,0,0,0,0,0,0,0,0,1,0,1,0
14997,87681,6,280,4,0,1,0,0,0,0,0,0,0,0,1,0,1,0
14998,87684,2,158,3,0,1,0,0,0,0,0,0,0,0,1,0,1,0

In [12]:
df=pd.get_dummies(df)
df

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department_RandD,department_accounting,department_hr,department_management,department_marketing,department_product_mng,department_sales,department_support,department_technical,salary_low,salary_medium
0,1003,2,157,3,0,1,0,0,0,0,0,0,0,1,0,0,1,0
1,1005,5,262,6,0,1,0,0,0,0,0,0,0,1,0,0,0,1
2,1486,7,272,4,0,1,0,0,0,0,0,0,0,1,0,0,0,1
3,1038,5,223,5,0,1,0,0,0,0,0,0,0,1,0,0,1,0
4,1057,2,159,3,0,1,0,0,0,0,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,0,0,0,0,0,0,0,1,0,1,0
14995,87673,2,160,3,0,1,0,0,0,0,0,0,0,0,1,0,1,0
14996,87679,2,143,3,0,1,0,0,0,0,0,0,0,0,1,0,1,0
14997,87681,6,280,4,0,1,0,0,0,0,0,0,0,0,1,0,1,0
14998,87684,2,158,3,0,1,0,0,0,0,0,0,0,0,1,0,1,0

In [13]:
df=pd.get_dummies(df,dtype=int)
df

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department_RandD,department_accounting,department_hr,department_management,department_marketing,department_product_mng,department_sales,department_support,department_technical,salary_low,salary_medium
0,1003,2,157,3,0,1,0,0,0,0,0,0,0,1,0,0,1,0
1,1005,5,262,6,0,1,0,0,0,0,0,0,0,1,0,0,0,1
2,1486,7,272,4,0,1,0,0,0,0,0,0,0,1,0,0,0,1
3,1038,5,223,5,0,1,0,0,0,0,0,0,0,1,0,0,1,0
4,1057,2,159,3,0,1,0,0,0,0,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,0,0,0,0,0,0,0,1,0,1,0
14995,87673,2,160,3,0,1,0,0,0,0,0,0,0,0,1,0,1,0
14996,87679,2,143,3,0,1,0,0,0,0,0,0,0,0,1,0,1,0
14997,87681,6,280,4,0,1,0,0,0,0,0,0,0,0,1,0,1,0
14998,87684,2,158,3,0,1,0,0,0,0,0,0,0,0,1,0,1,0

In [14]:
df1 = pd.read_csv( "https://raw.githubusercontent.com/Taj1920/Data-Analysis-Datasets/refs/heads/main/Datasets-Practice/blinkit_data.csv")
df1.head()

,Unnamed: 0,Item Fat Content,Item Identifier,Item Type,Outlet Establishment Year,Outlet Identifier,Outlet Location Type,Outlet Size,Outlet Type,Item Visibility,Item Weight,Sales,Rating
0,0,Regular,FDX32,Fruits and Vegetables,2012,OUT049,Tier 1,Medium,Supermarket Type1,0.100014,15.10,145.4786,5.0
1,1,Low Fat,NCB42,Health and Hygiene,2022,OUT018,Tier 3,Medium,Supermarket Type2,0.008596,11.80,115.3492,5.0
2,2,Regular,FDR28,Frozen Foods,2016,OUT046,Tier 1,Small,Supermarket Type1,0.025896,13.85,165.0210,5.0
3,3,Regular,FDL50,Canned,2014,OUT013,Tier 3,High,Supermarket Type1,0.042278,12.15,126.5046,5.0
4,4,Low Fat,DRI25,Soft Drinks,2015,OUT045,Tier 2,Small,Supermarket Type1,0.033970,19.60,55.1614,5.0

In [15]:
                            #question based on label Encoder and oneHot encoder
#Perform Label encoding on Items Fat Content and outlet Size columns and then Perform
                   #one Hot encoding on the whole datasets

In [16]:
# Load data
df = pd.read_csv("https://raw.githubusercontent.com/Taj1920/Data-Analysis-Datasets/main/Datasets-Practice/blinkit_data.csv")
df

,Unnamed: 0,Item Fat Content,Item Identifier,Item Type,Outlet Establishment Year,Outlet Identifier,Outlet Location Type,Outlet Size,Outlet Type,Item Visibility,Item Weight,Sales,Rating
0,0,Regular,FDX32,Fruits and Vegetables,2012,OUT049,Tier 1,Medium,Supermarket Type1,0.100014,15.100000,145.4786,5.0
1,1,Low Fat,NCB42,Health and Hygiene,2022,OUT018,Tier 3,Medium,Supermarket Type2,0.008596,11.800000,115.3492,5.0
2,2,Regular,FDR28,Frozen Foods,2016,OUT046,Tier 1,Small,Supermarket Type1,0.025896,13.850000,165.0210,5.0
3,3,Regular,FDL50,Canned,2014,OUT013,Tier 3,High,Supermarket Type1,0.042278,12.150000,126.5046,5.0
4,4,Low Fat,DRI25,Soft Drinks,2015,OUT045,Tier 2,Small,Supermarket Type1,0.033970,19.600000,55.1614,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8518,8518,Low Fat,NCT53,Health and Hygiene,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.000000,12.857645,164.5526,4.0
8519,8519,Low Fat,FDN09,Snack Foods,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.034706,12.857645,241.6828,4.0
8520,8520,Low Fat,DRE13,Soft Drinks,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.027571,12.857645,86.6198,4.0
8521,8521,Regular,FDT50,Dairy,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.107715,12.857645,97.8752,4.0
8522,8522,Regular,FDM58,Snack Foods,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.000000,12.857645,112.2544,4.0

In [17]:
df = df.drop('Unnamed: 0', axis=1)

In [18]:


# Create LabelEncoder object
LE = LabelEncoder()

# Label Encoding
df['Item Fat Content'] = LE.fit_transform(df['Item Fat Content'])
df['Outlet Size'] = LE.fit_transform(df['Outlet Size'])
df

,Item Fat Content,Item Identifier,Item Type,Outlet Establishment Year,Outlet Identifier,Outlet Location Type,Outlet Size,Outlet Type,Item Visibility,Item Weight,Sales,Rating
0,1,FDX32,Fruits and Vegetables,2012,OUT049,Tier 1,1,Supermarket Type1,0.100014,15.100000,145.4786,5.0
1,0,NCB42,Health and Hygiene,2022,OUT018,Tier 3,1,Supermarket Type2,0.008596,11.800000,115.3492,5.0
2,1,FDR28,Frozen Foods,2016,OUT046,Tier 1,2,Supermarket Type1,0.025896,13.850000,165.0210,5.0
3,1,FDL50,Canned,2014,OUT013,Tier 3,0,Supermarket Type1,0.042278,12.150000,126.5046,5.0
4,0,DRI25,Soft Drinks,2015,OUT045,Tier 2,2,Supermarket Type1,0.033970,19.600000,55.1614,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,0,NCT53,Health and Hygiene,2018,OUT027,Tier 3,1,Supermarket Type3,0.000000,12.857645,164.5526,4.0
8519,0,FDN09,Snack Foods,2018,OUT027,Tier 3,1,Supermarket Type3,0.034706,12.857645,241.6828,4.0
8520,0,DRE13,Soft Drinks,2018,OUT027,Tier 3,1,Supermarket Type3,0.027571,12.857645,86.6198,4.0
8521,1,FDT50,Dairy,2018,OUT027,Tier 3,1,Supermarket Type3,0.107715,12.857645,97.8752,4.0
8522,1,FDM58,Snack Foods,2018,OUT027,Tier 3,1,Supermarket Type3,0.000000,12.857645,112.2544,4.0

In [19]:

OHE = OneHotEncoder(sparse_output=False)
names = ['Item Identifier','Item Type','Outlet Identifier','Outlet Location Type','Outlet Type','Item Visibility','Item Weight','Sales','Rating']
# One-Hot Encoding
data = OHE.fit_transform(df[names])
# Get encoded column names
encoded_cols = OHE.get_feature_names_out(names)
# Create DataFrame
df_encoded = pd.DataFrame(data, columns=encoded_cols)
df_encoded.head()

,Item Identifier_DRA12,Item Identifier_DRA24,Item Identifier_DRA59,Item Identifier_DRB01,Item Identifier_DRB13,Item Identifier_DRB24,Item Identifier_DRB25,Item Identifier_DRB48,Item Identifier_DRC01,Item Identifier_DRC12,...,Rating_4.1,Rating_4.2,Rating_4.3,Rating_4.4,Rating_4.5,Rating_4.6,Rating_4.7,Rating_4.8,Rating_4.9,Rating_5.0
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [20]:
df_encoded.columns

Index(['Item Identifier_DRA12', 'Item Identifier_DRA24',
       'Item Identifier_DRA59', 'Item Identifier_DRB01',
       'Item Identifier_DRB13', 'Item Identifier_DRB24',
       'Item Identifier_DRB25', 'Item Identifier_DRB48',
       'Item Identifier_DRC01', 'Item Identifier_DRC12',
       ...
       'Rating_4.1', 'Rating_4.2', 'Rating_4.3', 'Rating_4.4', 'Rating_4.5',
       'Rating_4.6', 'Rating_4.7', 'Rating_4.8', 'Rating_4.9', 'Rating_5.0'],
      dtype='object', length=15865)

In [21]:
df1=df.copy()
df1.head()

,Item Fat Content,Item Identifier,Item Type,Outlet Establishment Year,Outlet Identifier,Outlet Location Type,Outlet Size,Outlet Type,Item Visibility,Item Weight,Sales,Rating
0,1,FDX32,Fruits and Vegetables,2012,OUT049,Tier 1,1,Supermarket Type1,0.100014,15.10,145.4786,5.0
1,0,NCB42,Health and Hygiene,2022,OUT018,Tier 3,1,Supermarket Type2,0.008596,11.80,115.3492,5.0
2,1,FDR28,Frozen Foods,2016,OUT046,Tier 1,2,Supermarket Type1,0.025896,13.85,165.0210,5.0
3,1,FDL50,Canned,2014,OUT013,Tier 3,0,Supermarket Type1,0.042278,12.15,126.5046,5.0
4,0,DRI25,Soft Drinks,2015,OUT045,Tier 2,2,Supermarket Type1,0.033970,19.60,55.1614,5.0

In [22]:
for col in df1.columns:
    if df1[col].dtype=='object':
     data=OHE.fit_transform(df1[[col]])
     names=OHE.get_feature_names_out([col])
     encoded_df=pd.DataFrame(data,columns= names)
     df1=df1.drop(col,axis=1)
     df1=pd.concat([df1,encoded_df],axis=1)

In [23]:
df1.head()

,Item Fat Content,Outlet Establishment Year,Outlet Size,Item Visibility,Item Weight,Sales,Rating,Item Identifier_DRA12,Item Identifier_DRA24,Item Identifier_DRA59,...,Outlet Identifier_OUT045,Outlet Identifier_OUT046,Outlet Identifier_OUT049,Outlet Location Type_Tier 1,Outlet Location Type_Tier 2,Outlet Location Type_Tier 3,Outlet Type_Grocery Store,Outlet Type_Supermarket Type1,Outlet Type_Supermarket Type2,Outlet Type_Supermarket Type3
0,1,2012,1,0.100014,15.10,145.4786,5.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
1,0,2022,1,0.008596,11.80,115.3492,5.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,1,2016,2,0.025896,13.85,165.0210,5.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
3,1,2014,0,0.042278,12.15,126.5046,5.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
4,0,2015,2,0.033970,19.60,55.1614,5.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0

In [24]:
OE=OrdinalEncoder()
df = pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/hr_data.csv')
df.head()

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low

In [25]:
df['salary'].unique()
OE = OrdinalEncoder(categories=[['low', 'medium', 'high']])
df['salary'] = OE.fit_transform(df[['salary']])
df
#print(df['salary'])

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,0.0
1,1005,5,262,6,0,1,0,sales,1.0
2,1486,7,272,4,0,1,0,sales,1.0
3,1038,5,223,5,0,1,0,sales,0.0
4,1057,2,159,3,0,1,0,sales,0.0
...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,support,0.0
14995,87673,2,160,3,0,1,0,support,0.0
14996,87679,2,143,3,0,1,0,support,0.0
14997,87681,6,280,4,0,1,0,support,0.0
14998,87684,2,158,3,0,1,0,support,0.0

In [26]:
norm=Normalizer()
df=pd.DataFrame({'Weight':[65,80,75],'Height':[170,130,110]})
df
df=norm.fit_transform(df)
scaled_df=norm.fit_transform(df)
scaled_df

array([[0.35713747, 0.93405183],
       [0.52409743, 0.85165832],
       [0.56333682, 0.82622734]])

In [27]:
stand=StandardScaler()
df=pd.DataFrame({'Weight':[65,80,75],'Height':[170,130,110]})
data=stand.fit_transform(df)
df=pd.DataFrame(data,columns=df.columns)
df

     Weight    Height
0 -1.336306  1.336306
1  1.069045 -0.267261
2  0.267261 -1.069045

In [28]:
# Sample dataset
'''data = {
    'Experience': [1, 2, 3, 4, 5, 6, 7, 8],
    'Salary': [25000, 30000, 35000, 40000, 45000, 50000, 55000, 60000]
}

df =  pd.DataFrame(data)

# Independent (X) and Dependent (y) variables
X = df[['Experience']]
y = df['Salary']

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Create model
lr = LinearRegression()

# Train model
lr.fit(X_train, y_train)

# Prediction
y_pred = lr.predict(X_test)

# Evaluation
print("Coefficient:", lr.coef_)
print("Intercept:", lr.intercept_)
print("MSE:", mean_squared_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))

# Predict salary for 10 years experience
salary = lr.predict([[10]])
print("Predicted Salary:", salary[0])'''

'data = {\n    \'Experience\': [1, 2, 3, 4, 5, 6, 7, 8],\n    \'Salary\': [25000, 30000, 35000, 40000, 45000, 50000, 55000, 60000]\n}\n\ndf =  pd.DataFrame(data)\n\n# Independent (X) and Dependent (y) variables\nX = df[[\'Experience\']]\ny = df[\'Salary\']\n\n# Split data into train and test sets\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y, test_size=0.2, random_state=42\n)\n\n# Create model\nlr = LinearRegression()\n\n# Train model\nlr.fit(X_train, y_train)\n\n# Prediction\ny_pred = lr.predict(X_test)\n\n# Evaluation\nprint("Coefficient:", lr.coef_)\nprint("Intercept:", lr.intercept_)\nprint("MSE:", mean_squared_error(y_test, y_pred))\nprint("R2 Score:", r2_score(y_test, y_pred))\n\n# Predict salary for 10 years experience\nsalary = lr.predict([[10]])\nprint("Predicted Salary:", salary[0])'

In [29]:
df=pd.read_csv('https://github.com/Jeevita-R/ML_datasets/raw/refs/heads/main/House_price_prediction.csv')
df.head()

,Unnamed: 0,Suburb,Rooms,Type,Method,SellerG,Regionname,Propertycount,Distance,CouncilArea,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price
0,1,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,1.0,202.0,160.2564,1480000.0
1,2,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,0.0,156.0,79.0000,1035000.0
2,4,Abbotsford,3,h,SP,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,2.0,0.0,134.0,150.0000,1465000.0
3,5,Abbotsford,3,h,PI,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,2.0,1.0,94.0,160.2564,850000.0
4,6,Abbotsford,4,h,VB,Nelson,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,1.0,2.0,120.0,142.0000,1600000.0

In [30]:
df=pd.get_dummies(df,drop_first=True,dtype=int)
df

,Unnamed: 0,Rooms,Propertycount,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price,...,CouncilArea_Moorabool Shire Council,CouncilArea_Moreland City Council,CouncilArea_Nillumbik Shire Council,CouncilArea_Port Phillip City Council,CouncilArea_Stonnington City Council,CouncilArea_Whitehorse City Council,CouncilArea_Whittlesea City Council,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council
0,1,2,4019.0,2.5,2.0,1.0,1.0,202.000000,160.2564,1480000.0,...,0,0,0,0,0,0,0,0,1,0
1,2,2,4019.0,2.5,2.0,1.0,0.0,156.000000,79.0000,1035000.0,...,0,0,0,0,0,0,0,0,1,0
2,4,3,4019.0,2.5,3.0,2.0,0.0,134.000000,150.0000,1465000.0,...,0,0,0,0,0,0,0,0,1,0
3,5,3,4019.0,2.5,3.0,2.0,1.0,94.000000,160.2564,850000.0,...,0,0,0,0,0,0,0,0,1,0
4,6,4,4019.0,2.5,3.0,1.0,2.0,120.000000,142.0000,1600000.0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27239,34852,4,6543.0,6.3,4.0,1.0,3.0,593.000000,160.2564,1480000.0,...,0,0,0,0,0,0,0,0,0,0
27240,34853,2,6543.0,6.3,2.0,2.0,1.0,98.000000,104.0000,888000.0,...,0,0,0,0,0,0,0,0,0,0
27241,34854,2,6543.0,6.3,2.0,1.0,2.0,220.000000,120.0000,705000.0,...,0,0,0,0,0,0,0,0,0,0
27242,34855,3,6543.0,6.3,0.0,0.0,0.0,593.598993,160.2564,1140000.0,...,0,0,0,0,0,0,0,0,0,0
27243,34856,2,6543.0,6.3,2.0,1.0,0.0,250.000000,103.0000,1020000.0,...,0,0,0,0,0,0,0,0,0,0

In [31]:
df=df.drop("Unnamed: 0",axis=1)
df

,Rooms,Propertycount,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price,Suburb_Aberfeldie,...,CouncilArea_Moorabool Shire Council,CouncilArea_Moreland City Council,CouncilArea_Nillumbik Shire Council,CouncilArea_Port Phillip City Council,CouncilArea_Stonnington City Council,CouncilArea_Whitehorse City Council,CouncilArea_Whittlesea City Council,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council
0,2,4019.0,2.5,2.0,1.0,1.0,202.000000,160.2564,1480000.0,0,...,0,0,0,0,0,0,0,0,1,0
1,2,4019.0,2.5,2.0,1.0,0.0,156.000000,79.0000,1035000.0,0,...,0,0,0,0,0,0,0,0,1,0
2,3,4019.0,2.5,3.0,2.0,0.0,134.000000,150.0000,1465000.0,0,...,0,0,0,0,0,0,0,0,1,0
3,3,4019.0,2.5,3.0,2.0,1.0,94.000000,160.2564,850000.0,0,...,0,0,0,0,0,0,0,0,1,0
4,4,4019.0,2.5,3.0,1.0,2.0,120.000000,142.0000,1600000.0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27239,4,6543.0,6.3,4.0,1.0,3.0,593.000000,160.2564,1480000.0,0,...,0,0,0,0,0,0,0,0,0,0
27240,2,6543.0,6.3,2.0,2.0,1.0,98.000000,104.0000,888000.0,0,...,0,0,0,0,0,0,0,0,0,0
27241,2,6543.0,6.3,2.0,1.0,2.0,220.000000,120.0000,705000.0,0,...,0,0,0,0,0,0,0,0,0,0
27242,3,6543.0,6.3,0.0,0.0,0.0,593.598993,160.2564,1140000.0,0,...,0,0,0,0,0,0,0,0,0,0
27243,2,6543.0,6.3,2.0,1.0,0.0,250.000000,103.0000,1020000.0,0,...,0,0,0,0,0,0,0,0,0,0

In [32]:
#divide the data
X=df.drop ('Price',axis=1)
y=df['Price']
X

,Rooms,Propertycount,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Suburb_Aberfeldie,Suburb_Airport West,...,CouncilArea_Moorabool Shire Council,CouncilArea_Moreland City Council,CouncilArea_Nillumbik Shire Council,CouncilArea_Port Phillip City Council,CouncilArea_Stonnington City Council,CouncilArea_Whitehorse City Council,CouncilArea_Whittlesea City Council,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council
0,2,4019.0,2.5,2.0,1.0,1.0,202.000000,160.2564,0,0,...,0,0,0,0,0,0,0,0,1,0
1,2,4019.0,2.5,2.0,1.0,0.0,156.000000,79.0000,0,0,...,0,0,0,0,0,0,0,0,1,0
2,3,4019.0,2.5,3.0,2.0,0.0,134.000000,150.0000,0,0,...,0,0,0,0,0,0,0,0,1,0
3,3,4019.0,2.5,3.0,2.0,1.0,94.000000,160.2564,0,0,...,0,0,0,0,0,0,0,0,1,0
4,4,4019.0,2.5,3.0,1.0,2.0,120.000000,142.0000,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27239,4,6543.0,6.3,4.0,1.0,3.0,593.000000,160.2564,0,0,...,0,0,0,0,0,0,0,0,0,0
27240,2,6543.0,6.3,2.0,2.0,1.0,98.000000,104.0000,0,0,...,0,0,0,0,0,0,0,0,0,0
27241,2,6543.0,6.3,2.0,1.0,2.0,220.000000,120.0000,0,0,...,0,0,0,0,0,0,0,0,0,0
27242,3,6543.0,6.3,0.0,0.0,0.0,593.598993,160.2564,0,0,...,0,0,0,0,0,0,0,0,0,0
27243,2,6543.0,6.3,2.0,1.0,0.0,250.000000,103.0000,0,0,...,0,0,0,0,0,0,0,0,0,0

In [33]:
Xtrain,Xtest,ytrain,ytest=train_test_split(X,y,test_size=0.3,random_state=42) #random state if not provide data shuffle between testing and training

In [34]:
Lr=LinearRegression()
Lr.fit(Xtrain,ytrain)
LinearRegression()

LinearRegression()

In [35]:
ypred=Lr.predict(Xtest)
ypred

array([ 857187.80821225, 1356101.7607676 ,  639962.92487671, ...,
        573461.17670821, 1057060.90595005,  832123.09601173],
      shape=(8174,))

In [36]:
print("Training",Lr.score(Xtrain,ytrain))
print("Testing",Lr.score(Xtest,ytest))

Training 0.6745987124668316
Testing 0.6714746150307309

In [37]:
print('MAE',mean_absolute_error(ytest,ypred))

MAE 234926.94345956045

In [38]:
#RIEDGE REGRESSION
ridge=Ridge(alpha=1)
ridge.fit(Xtrain,ytrain)

Ridge(alpha=1)

In [39]:
ypred=ridge.predict(Xtest)
ypred

array([ 858978.61870282, 1353776.93145941,  647558.08069872, ...,
        574536.04968511, 1060670.89317842,  835431.83696239],
      shape=(8174,))

In [40]:
print("Training Err",ridge.score(Xtrain,ytrain))
print("Training Err",ridge.score(Xtest,ytest))

Training Err 0.6739175006196745
Training Err 0.6776450968954018

In [41]:
lasso=Lasso(alpha=5)
lasso.fit(Xtrain,ytrain)
print(lasso)
#Lasso(alpha=55)

Lasso(alpha=5)

c:\Users\ASUS\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.279995e+15, tolerance: 7.845e+11
  model = cd_fast.enet_coordinate_descent(

In [42]:
ypred=lasso.predict(Xtest)
ypred

array([ 858125.34967117, 1354635.11653032,  646628.21713465, ...,
        575344.35699276, 1058819.82196667,  829707.4125857 ],
      shape=(8174,))

In [43]:
print("Training Eff",lasso.score(Xtrain,ytrain))
print("Training Eff",lasso.score(Xtest,ytest))

Training Eff 0.6743976722999689
Training Eff 0.6743780158021235